<?php
/**
 * µDashboard - Dashboard and fioritures.
 */

use MakinaCorpus\Drupal\Dashboard\Controller\ActionProcessorController;
use MakinaCorpus\Drupal\Dashboard\Controller\AjaxPageController;
use MakinaCorpus\Drupal\Dashboard\Page\DatasourceInterface;
use MakinaCorpus\Drupal\Dashboard\Page\DisplayInterface;
use MakinaCorpus\Drupal\Dashboard\Page\Page;
use MakinaCorpus\Drupal\Dashboard\Table\AdminTable;
use MakinaCorpus\Drupal\Dashboard\TransactionHandler;

/**
 * View mode for content display.
 */
const UDASHBOARD_VIEW_MODE_CONTENTADMIN = 'contentadmin';

/**
 * View mode for cart display.
 */
const UDASHBOARD_VIEW_MODE_FAVORITE = 'favorite';

/**
 * Image style for search.
 */
const UDASHBOARD_STYLE_CONTENTADMIN = 'contentadmin';

/**
 * Image style for favorite.
 */
const UDASHBOARD_STYLE_FAVORITE = 'favorite';

/**
 * Use contextual pane permission.
 */
const UDASHBOARD_PERM_USE_CONTEXT_PANE = 'use contextual pane';

/**
 * Implements hook_permission().
 */
function udashboard_permission() {
  return [
    UDASHBOARD_PERM_USE_CONTEXT_PANE => [
      'title' => t("Use contextual pane"),
    ],
  ];
}

/**
 * Implements hook_admin_custom_theme().
 */
function udashboard_custom_theme() {
  if (module_exists('ucms_site') && ucms_site_is_master()) {
    return variable_get('admin_theme', variable_get('theme_default', 'bartik'));
  }
}

/**
 * Implements hook_menu().
 */
function udashboard_menu() {

  $items = [];

  $items['home'] = [
    'page callback'     => 'udashboard_home',
    'access callback'   => true,
    'type'              => MENU_CALLBACK,
  ];
  $items['admin/dashboard'] = [
    'title'             => "Dashboard",
    'page callback'     => 'udashboard_page',
    'access arguments'  => ['access administration pages'],
    'type'              => MENU_NORMAL_ITEM,
    'file'              => 'udashboard.pages.inc',
  ];
  $items['admin/action/process'] = [
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [ActionProcessorController::class .  '::process'],
    'type'              => MENU_CALLBACK,
  ];
  $items['admin/page/refresh'] = [
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [AjaxPageController::class .  '::refresh'],
    'type'              => MENU_CALLBACK,
  ];
  $items['admin/page/search'] = [
    'page callback'     => 'sf_dic_page',
    'page arguments'    => [AjaxPageController::class .  '::search'],
    'type'              => MENU_CALLBACK,
  ];

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function udashboard_menu_alter(&$items) {
  $container = \Drupal::getContainer();

  if ($container->getParameter('udashboard.breadcrumb_alter', false)) {
    // Remove all the unnecessary pages using the 'access administration pages'
    // or whatever else permission the users may have.
    foreach ([
      'admin/compact',
      'admin/config',
      'admin/config/content',
      'admin/config/development',
      'admin/config/media',
      'admin/config/regional',
      'admin/config/search',
      'admin/config/services',
      'admin/config/system',
      'admin/config/user-interface',
      'admin/config/workflow',
      'admin/index',
      'admin/reports/status/rebuild',
      'admin/structure',
    ] as $path) {
      $items[$path]['access arguments'] = ['non existing permission'];
    }

    // Single override where we change the 'admin' home page.
    $items['admin'] = [
      'title'             => "Administration",
      'page callback'     => 'udashboard_admin_redirect',
      'access arguments'  => ['access administration pages'],
      'type'              => MENU_CALLBACK,
      // Required to avoid file_scan_directory() calls when rebuilding menu.
      'module'            => 'udashboard',
    ];
  }
}

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function udashboard_menu_breadcrumb_alter(&$active_trail, $item) {
  $container = \Drupal::getContainer();

  if ($container->getParameter('udashboard.breadcrumb_alter', false) && path_is_admin(current_path())) {

    // Remove the useless 'Home' link. Using array_splice() will reset the
    // numerical indexes within the array allowing the rest of the function
    // to work properly.
    array_splice($active_trail, 0, 1);

    // Remove any item that would be just 'admin', this specific admin page
    // is to be hidden within our custom admin, it does not make sense to
    // keep it.
    foreach ($active_trail as $index => $item) {
      if ('admin' === $item['href']) {
        array_splice($active_trail, $index, 1);
      }
    }

    // Ensure the first item is the dashboard item, if not inject it,
    // dashboard is the main entry point for everything. Please note that if
    // the current path is the dashboard, there is not other alteration to be
    // done so we'll return early.
    if ('admin/dashboard' === current_path()) {
      return;
    }

    if ('admin/dashboard' !== $active_trail[0]['href']) {
      array_unshift($active_trail, [
        'title' => t("Dashboard"),
        'href'  => 'admin/dahsboard',
        'localized_options' => [],
      ]);
    }

    $manager = ucms_site_manager();
    if ($manager->hasContext()) {
      array_splice($active_trail, 1, 0, [
        [
          'title' => check_plain($manager->getContext()->getAdminTitle()),
          'href'  => '<front>',
          'localized_options' => [],
        ]
      ]);
    }
  }
}

/**
 * Implements hook_entity_info_alter().
 */
function udashboard_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes'][UDASHBOARD_VIEW_MODE_CONTENTADMIN] = [
    'label' => t('Content admin display'),
    'custom settings' => false,
  ];
  $entity_info['node']['view modes'][UDASHBOARD_VIEW_MODE_FAVORITE] = [
    'label' => t('Favorite in cart'),
    'custom settings' => false,
  ];
}

/**
 * Implements hook_image_default_styles().
 */
function udashboard_image_default_styles() {
  return [
    UDASHBOARD_STYLE_CONTENTADMIN => [
      'effects' => [[
        'name' => 'image_scale_and_crop',
        'data' => [
          'width'   => 285, // ~ col-md-3
          'height'  => 285,
          'upscale' => 1,
        ],
        'weight' => 0,
      ]],
    ],
    UDASHBOARD_STYLE_FAVORITE => [
      'effects' => [[
        'name' => 'image_scale_and_crop',
        'data' => [
          'width'   => 120, // ~ col-md-6 in cart
          'height'  => 120,
          'upscale' => 1,
        ],
        'weight' => 0,
      ]],
    ],
  ];
}

/**
 * Implements hook_node_view_alter().
 *
 * Removes links from nodes when in build modes used for back office.
 */
function udashboard_node_view_alter(&$build) {
  switch ($build['#view_mode']) {

    case UDASHBOARD_VIEW_MODE_CONTENTADMIN:
    case UDASHBOARD_VIEW_MODE_FAVORITE:
      $build['links']['#access'] = false;
      break;
  }
}

/**
 * Implements hook_preprocess_node().
 *
 * Removes submitted information and adds necessary stuff for JS.
 */
function udashboard_preprocess_node(&$variables) {

  // Adds the data-nid attribute on all nodes.
  // @todo exclude cart as of now else it'll trigger bugs:
  //   - remove custom template for cart items
  if ('favorite' !== $variables['view_mode']) {
    $variables['attributes_array']['data-nid'] = $variables['node']->nid;
    $variables['attributes_array']['data-viewmode'] = $variables['view_mode'];
  }

  switch ($variables['view_mode']) {

    case UDASHBOARD_VIEW_MODE_CONTENTADMIN:
    case UDASHBOARD_VIEW_MODE_FAVORITE:
      $variables['submitted'] = null;
      break;
  }
}

/**
 * Implements hook_field_attach_view_alter().
 *
 * @todo move to a custom module!
 */
function udashboard_field_attach_view_alter(&$output, $context) {

  $mapping = [
    UDASHBOARD_VIEW_MODE_CONTENTADMIN => UDASHBOARD_STYLE_CONTENTADMIN,
    UDASHBOARD_VIEW_MODE_FAVORITE     => UDASHBOARD_STYLE_FAVORITE,
  ];

  // Only work on nodes and some view modes.
  if ('node' !== $context['entity_type'] || empty($mapping[$context['view_mode']])) {
    return;
  }

  $view_mode = $mapping[$context['view_mode']];

  // Force image style on content viewed in admin mode
  $image_found = false;
  if (in_array($context['view_mode'], array_keys($mapping))) {
    foreach (element_children($output) as $field_name) {
      $element = &$output[$field_name];
      $image_found = _udashboard_find_image_recursive($element, $view_mode);
      if ($image_found) {
        break;
      }
    }
  }

  if (!$image_found) {
    // Add a default image for other medias/content.
    $icon_mapping = [
      // media
      'document'  => 'file',
      'video'     => 'film',
      // Composite content
      'list_type' => 'list',
      'search'    => 'search',
      'geosearch' => 'map-marker',
      // other content
      'form'      => 'list-alt',
      'job_offer' => 'briefcase',
    ];
    $markup = '<div class="udashboard-default-icon img-thumbnail"><div><div>';
    if (!empty($icon_mapping[$output['#bundle']])) {
      $markup .= '<span class="glyphicon glyphicon-' . $icon_mapping[$output['#bundle']] . '"></span>';
    }
    else {
      $markup .= '<span>' . node_type_get_name($context['entity']) . '</span>';
    }
    $markup .= '</div></div></div>';
    $output['default_icon'] = ['#markup' => $markup];
  }

  // Add icon relative to meta content type
  $icon_mapping = ['content' => 'file', 'media'   => 'picture'];
  $meta_type = null;
  if (module_exists('ucms_contrib')) {
    $typeHandler = ucms_contrib_type_handler_get();
    foreach ($typeHandler->getTabs() as $tab => $label) {
      if (in_array($output['#bundle'], $typeHandler->getTabTypes($tab))) {
        $meta_type = $tab;
      }
    }
  }

  $output['metadata']['#prefix'] = '<div class="ucms-metadata">';
  $output['metadata']['#suffix'] = '</div>';
  if (!$context['entity']->status) {
    $output['metadata']['status_icon'] = [
      '#markup' => '<span class="udashboard-unpublished-icon glyphicon glyphicon-warning-sign"></span>',
      '#weight' => 5,
    ];
  }
  if ($meta_type && isset($icon_mapping[$meta_type])) {
    $output['metadata']['type_icon'] = [
      '#markup' => '<span class="udashboard-type-icon glyphicon glyphicon-' . $icon_mapping[$meta_type] . '"></span>',
      '#weight' => 10,
    ];
  }
}

/**
 * @param $element
 * @param $view_mode
 * @return bool
 */
function _udashboard_find_image_recursive(&$element, $view_mode) {
  $image_found = false;

  if (isset($element['#field_type']) && $element['#field_type'] == 'image' && ($element['#formatter'] == 'image' || $element['#formatter'] == 'iresponsive')) {
    foreach (element_children($element) as $delta) {
      if ($delta === 0) {
        $image_found = true;
        // Force image style related to view mode.
        $element[$delta]['#image_style'] = $view_mode;
        $element[$delta]['#item']['attributes']['class'] = 'img-responsive img-rounded';
      } else {
        // Hide other image for slideshows.
        $element[$delta]['#access'] = false;
      }
    }
  } else if (count(element_children($element))) {
    foreach (element_children($element) as $key) {
      $image_found = _ucms_contrib_find_image_recursive($element[$key], $view_mode);
      if ($image_found) {
        $element = $element[$key];
        return TRUE;
      }
    }
  } else {
    $element['#access'] = false;
  }

  return $image_found;
}

/**
 * Do it in a transaction!
 */
function udashboard_transaction_form() {
  if ('GET' !== \Drupal::requestStack()->getCurrentRequest()->getMethod()) {
    $args = func_get_args();
    /** @var $helper TransactionHandler */
    $helper = \Drupal::get('udashboard.transaction_handler');
    $helper->run(function () use ($args) {
      return sf_dic_page_form($args);
    });
  } else {
    return sf_dic_page_form(func_get_args());
  }
}

/**
 * Menu callback.
 */
function udashboard_admin_redirect() {
  drupal_goto('admin/dashboard');
}

/**
 * Admin home.
 */
function udashboard_home() {
  if (drupal_is_cli()) {
    return; // Make drush happy.
  }
  if (ucms_site_manager()->hasContext()) {
    return; // Let sites handle their own frontpage.
  }
  if (!user_is_logged_in()) {
    drupal_goto('user/login');
  }
  drupal_goto('admin/dashboard');
}

/**
 * Implements hook_user_login().
 */
function udashboard_user_login(&$edit, $account) {
  // When a user logs in, he must be redirected to main dashboard.
  if (drupal_is_cli()) {
    return; // Make drush happy.
  }
  if (module_exists('ucms_site') && ucms_site_manager()->hasContext()) {
    return; // Let sites handle their own frontpage.
  }
  $GLOBALS['udashboard_login_redirect'] = true;
}

/**
 * Implements hook_drupal_goto_alter().
 */
function udashboard_drupal_goto_alter(&$path, &$options, &$http_response_code) {
  // This is the most proper way to provide a user login redirect.
  if (!empty($GLOBALS['udashboard_login_redirect'])) {
    if (isset($_GET['destination'])) {
      return; // Do not alter proper redirect.
    }
    $path = 'admin/dashboard';
  }
}

/**
 * Fetch a specific page.
 *
 * Sad but true story, because we are not going to inject the controllers we
 * are forced to keep this in the procedural code, in order for page callbacks
 * to be able to use it.
 *
 * @param DatasourceInterface $datasource
 * @param DisplayInterface $display
 * @param string[] $suggestions
 *   An arbitrary number of string which will derivate the template suggestions
 *   for example, let's say you set here ['foo', 'bar'], the derivative template
 *   to use will be: 'udashboard-page-list--foo--bar'.
 *
 * @return Page
 *
 * @deprecated
 */
function udashboard_page_get(DatasourceInterface $datasource, DisplayInterface $display, $suggestions) {
  trigger_error("Please write controllers and services instead.", E_USER_DEPRECATED);
  /** @var \MakinaCorpus\Drupal\Dashboard\AdminWidgetFactory $factory */
  $factory = \Drupal::service('udashboard.admin_widget_factory');
  return $factory->getPage($datasource, $display, $suggestions);
}

/**
 * Create an admin table.
 *
 * Sad but true story, because we are not going to inject the controllers we
 * are forced to keep this in the procedural code, in order for page callbacks
 * to be able to use it.
 *
 * @param string $name
 * @param mixed[] $attributes
 *
 * @return AdminTable
 *
 * @deprecated
 */
function udashboard_admin_table_get($name, array $attributes = []) {
  trigger_error("Please write controllers and services instead.", E_USER_DEPRECATED);
  /** @var \MakinaCorpus\Drupal\Dashboard\AdminWidgetFactory $factory */
  $factory = \Drupal::service('udashboard.admin_widget_factory');
  return $factory->getTable($name, $attributes);
}

/**
 * Get dashboard.
 *
 * @return \MakinaCorpus\Drupal\Dashboard\Portlet\PortletRegistry
 *
 * @deprecated
 *   Will be replaced by services one day.
 */
function udashboard_portlet_registry_get() {
  trigger_error("Please write controllers and services instead.", E_USER_DEPRECATED);
  return \Drupal::service('udashboard.portlet_registry');
}

/**
 * Implements hook_theme().
 */
function udashboard_theme() {
  return [
    'udashboard_actions' => [
      'variables' => [
        'item'        => null,
        'actions'     => [],
        'mode'        => 'link',
        'title'       => '',
        'icon'        => null,
        'show_title'  => false,
      ],
      'template'  => 'udashboard-actions',
    ],
    'udashboard_context' => [
      'variables' => [
        'tabs'        => [],
        'items'       => [],
        'actions'     => [],
      ],
      'template' => 'udashboard-context',
    ],
    'udashboard_page' => [
      'variables' => ['portlets' => []],
      'template'  => 'udashboard-page',
    ],
    'udashboard_page_list' => [
      'variables' => [
        'display'     => null,
        'filters'     => [],
        'items'       => [],
        'search'      => null,
        'pager'       => null,
        'sort_field'  => null,
        'sort_order'  => null,
      ],
      'template' => 'udashboard-page-list',
    ],
    'udashboard_top' => [
      'variables' => ['links' => []],
      'template'  => 'udashboard-top',
    ],
    'description_list' => [
      'variables' => ['items' => []],
      'template'  => 'templates/description-list',
    ],
  ];
}

/**
 * Implements hook_page_build().
 */
function udashboard_page_build(&$page) {
  $container = \Drupal::getContainer();

  if ($container->getParameter('udashboard.context_pane_enable') &&
      user_access(UDASHBOARD_PERM_USE_CONTEXT_PANE)
  ) {
    /** @var \MakinaCorpus\Drupal\Dashboard\Context\ContextPane $context */
    $context = \Drupal::service('udashboard.context');
    $context->init();

    $actions = [];
    foreach ($context->getActions() as $data) {
      if (is_array($data['actions']) && count($data['actions']) && reset($data['actions']) instanceof \MakinaCorpus\Drupal\Dashboard\Action\Action) {
        $actions[] = [
          '#theme'      => 'udashboard_actions',
          '#actions'    => $data['actions'],
          '#title'      => $data['title'],
          '#icon'       => $data['icon'],
          '#show_title' => $data['showTitle'],
        ];
      } else {
        $actions[] = $data['actions'];
      }
    }
    $js_setting = [
      'type' => 'setting',
      'data' => [
        'udashboard' => [
          'defaultPane' => $context->getDefaultTab(),
          'isOpened'    => $context->isOpened(),
        ],
      ],
    ];
    $page['page_top']['ucontext_pane'] = [
      '#theme'    => 'udashboard_context',
      '#items'    => $context->getAll(),
      '#tabs'     => $context->getTabs(),
      '#actions'  => $actions,
      '#attached' => [
        'library' => [['udashboard', 'udashboard'], ['system', 'jquery.once']],
        'js'      => [$js_setting],
      ],
    ];
  }

  if ($container->getParameter('udashboard.toolbar_enable') &&
      (user_is_logged_in() || path_is_admin(current_path()))
  ) {
    $links = menu_navigation_links('main-menu');
    foreach ($links as $i => $link) {
      if ($link['href'] === 'user/logout' && user_access('access administration pages')) {
        $links[$i]['href'] = ucms_site_master_absolute_url() . '/user/logout';
        $links[$i]['absolute'] = true;
      }
    }

    $page['page_top']['udashboard_top'] = [
      '#theme' => 'udashboard_top',
      '#links' => [
        '#theme' => 'links__main_menu',
        '#links' => $links,
      ],
    ];
  }
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_udashboard_page_list(&$variables) {
  /** @var $display \MakinaCorpus\Drupal\Dashboard\Page\DisplayInterface */
  $display = $variables['display'];
  $variables['displayView']   = $display->render($variables['items']);
  $variables['displayLinks']  = $display->renderLinks(current_path());
}

/**
 * Render item actions.
 *
 * @param array $variables
 */
function template_preprocess_udashboard_actions(&$variables) {
  // Clean title that may be === 0
  if (empty($variables['title'])) {
    $variables['title'] = '';
  }
  if (empty($variables['icon'])) {
    $variables['icon'] = '';
  }
  if (!isset($variables['show_title'])) {
    $variables['show_title'] = empty($variables['icon']);
  }

  foreach ($variables['actions'] as $key => $action) {
    /** @var $action \MakinaCorpus\Drupal\Dashboard\Action\Action */
    // Remove actions for which the path is the same.
    if (current_path() === $action->getURI()) {
      continue;
    }
    if ($action->isPrimary()) {
      $target = 'primary';
    } else {
      $target = 'secondary';
    }

    $item = [];
    $item['separator'] = false;
    $item['options']  = $action->getLinkOptions();
    $item['options'] += ['attributes' => []];
    if (isset($item['options']['attributes']['class'])) {
      $item['options']['attributes']['class'] = implode(' ', $item['options']['attributes']['class']);
    } else {
      $item['options']['attributes']['class'] = '';
    }
    if ('primary' === $target) {
      $item['options']['attributes']['class'] .= ' btn btn-default';
    }
    $item['title']    = $action->getTitle();
    $item['href']     = $action->getURI();
    $item['priority'] = $action->getPriority();
    $item['icon']     = $action->getIcon();

    $variables[$target][$action->getGroup()][$key] = $item;
  }

  foreach (['primary', 'secondary'] as $target) {
    if (isset($variables[$target])) {
      foreach ($variables[$target] as &$group) {
        usort($group, function ($a, $b) {
          return $a['priority'] - $b['priority'];
        });
      }
    }
  }

  if ($variables['mode']) {
    $variables['mode'] === 'icon';
  }
}

/**
 * Implements hook_library().
 */
function udashboard_library() {
  return [
    'udashboard' => [
      'title'        => 'µDashboard',
      'version'      => '0.1',
      'js'           => [
        drupal_get_path('module', 'udashboard') . '/udashboard.js' => [],
        drupal_get_path('module', 'udashboard') . '/jquery.typewatch.js' => [],
        drupal_get_path('module', 'udashboard') . '/udashboard.page.js' => [],
      ],
      'css'          => [
        drupal_get_path('module', 'udashboard') . '/udashboard.css' => ['type'  => 'file', 'media' => 'screen']
      ],
      'dependencies' => [['system', 'jquery.cookie']],
    ],
  ];
}
