services:

    calista.context_pane:
        public: false
        class: MakinaCorpus\Calista\Context\ContextPane
        arguments: ['@event_dispatcher']

    calista.twig.context_extension:
        public: false
        class: MakinaCorpus\Calista\Twig\ContextPaneExtension
        arguments: ['@calista.context_pane']
        tags: [{name: twig.extension}]
