services:

    calista.view_factory:
        class: MakinaCorpus\Calista\DependencyInjection\ViewFactory
        arguments: ['@service_container']

    calista.action_provider_registry:
        public: false
        class: MakinaCorpus\Calista\Action\ActionRegistry

    # View implementations
    calista.view.twig_page:
        public: true
        class: MakinaCorpus\Calista\View\Html\TwigView
        arguments: ['@twig', '@event_dispatcher']
        tags: [{name: calista.view, id: twig_page}]
    calista.view.twig_form_page:
        public: true
        class: MakinaCorpus\Calista\View\Html\FormTwigView
        arguments: ['@twig', '@event_dispatcher']
        tags: [{name: calista.view, id: twig_form_page}]

    # Twig extensions
    calista.twig.action_extension:
        public: false
        class: MakinaCorpus\Calista\Twig\ActionExtension
        arguments: ['@calista.action_provider_registry', '@request_stack', '@router']
        tags: [{name: twig.extension}]
    calista.twig.page_extension:
        public: false
        class: MakinaCorpus\Calista\Twig\PageExtension
        arguments: ['@request_stack', '@property_accessor', '@property_info']
        tags: [{name: twig.extension}]
