parameters:
    calista.redirect_router.parameter_name: destination

services:

    calista.view_factory:
        public: true
        class: MakinaCorpus\Calista\DependencyInjection\ViewFactory
        arguments: ['@service_container']

    calista.page_renderer:
        public: true
        class: MakinaCorpus\Calista\Controller\PageRenderer
        arguments: ['@calista.view_factory']

    calista.action_provider_registry:
        public: false
        class: MakinaCorpus\Calista\Action\ActionRegistry

    calista.redirect_router:
        public: true
        class: MakinaCorpus\Calista\Routing\RedirectRouter
        decorates: router
        arguments: ['@calista.redirect_router.inner', '@request_stack', '%calista.redirect_router.parameter_name%']
        tags: [{name: kernel.event_subscriber}]

    calista.property_renderer:
        public: false
        class: MakinaCorpus\Calista\View\PropertyRenderer
        arguments: ['@property_accessor', '@property_info']

    # Twig extensions
    calista.twig.action_extension:
        public: false
        class: MakinaCorpus\Calista\Twig\ActionExtension
        arguments: ['@calista.action_provider_registry', '@request_stack', '@router']
        tags: [{name: twig.extension}]
    calista.twig.page_extension:
        public: false
        class: MakinaCorpus\Calista\Twig\PageExtension
        arguments: ['@request_stack', '@calista.property_renderer']
        tags: [{name: twig.extension}]
