services:

    calista.view.csv_stream:
        public: true
        class: MakinaCorpus\Calista\View\Stream\CsvStreamView
        arguments: ['@calista.property_renderer']
        tags: [{name: calista.view, id: csv_stream}]

    calista.view.twig_page:
        public: true
        class: MakinaCorpus\Calista\View\Html\TwigView
        arguments: ['@twig', '@event_dispatcher']
        tags: [{name: calista.view, id: twig_page}]

    calista.view.twig_form_page:
        public: true
        class: MakinaCorpus\Calista\View\Html\FormTwigView
        arguments: ['@twig', '@event_dispatcher', '@?form.factory']
        tags: [{name: calista.view, id: twig_form_page}]
